[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.23"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
via_ir = false

# Load .env file automatically
fs_permissions = [{ access = "read", path = "./" }]
env_file = ".env"

# Remappings
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/=lib/chainlink/"
]

# Test configuration
ffi = false
verbosity = 2

# Deployment configuration
# [profile.default.etherscan]
# status_sepolia = { key = "${ETHERSCAN_API_KEY}" }

[profile.default.rpc_endpoints]
status_sepolia = "${RPC_ENDPOINT}"
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

