[build]
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  NPM_FLAGS = "--no-frozen-lockfile"
  PNPM_FLAGS = "--no-frozen-lockfile"

[context.production.environment]
  NODE_VERSION = "22"

